import "./globals.css";
import { AuthProvider } from "@/components/providers/AuthProvider";
import Navbar from "@/components/layout/Navbar";
import FloatingChatButton from "@/components/ui/FloatingChatButton";
import { CartProvider } from "@/context/CartContext"
export const metadata = {
  title: "Shalaan Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <CartProvider>
          <AuthProvider>
            <Navbar />
            <FloatingChatButton />
            <main>{children}</main>
          </AuthProvider>
        </CartProvider>
      </body>
    </html>
  );
}
